# Generated by Django 5.2.6 on 2025-09-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100)),
                ('DirectorName', models.CharField(max_length=100)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('SciFi', 'Sci-Fi')], max_length=20)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
